#!/usr/bin/env ruby

# =============================================================================
# Load dependencies
# -----------------------------------------------------------------------------

# @see: http://stackoverflow.com/a/5998961/192196
$LOAD_PATH.unshift File.dirname(__FILE__)
require 'optparse'
require 'ostruct'
require 'pp'

require 'election_data'

# =============================================================================
# Application
# -----------------------------------------------------------------------------

class Parser
  def self.parse(args)
    options = OpenStruct.new

    opt_parser = OptionParser.new do |opts|
      opts.banner = "Parses election data given student voter lists and election meta-data to better understand\nvoter behaviour.\n\nUsage: #{opts.program_name} [options]"

      opts.separator ''
      opts.separator 'Required options:'

      # Mandatory argument.
      opts.on('-v', '--voters A.csv,B.csv', Array,
              'Required. The files that collectively create the voters list.') do |list|
        options.voter_list = list
      end

      # Mandatory argument.
      opts.on('-r', '--results X.txt,Y.txt', Array,
              'Required. The files that collectively create the results.') do |res|
        options.results = res
      end

      opts.separator ''
      opts.separator 'Common options:'

      opts.on_tail('-h', '--help', 'Show this message') do
        puts opts
        exit
      end

      opts.on_tail('--version', 'Show version') do
        puts OptionParser::Version.join('.')
        exit
      end
    end
    opt_parser.parse!(args)

    raise OptionParser::MissingArgument, "no 'voter_list' option specified  as a parameter" if options.voter_list.nil?
    raise OptionParser::MissingArgument, "no 'results' option specified  as a parameter" if options.results.nil?

    options
  end
end

options = Parser.parse(ARGV)

election_data = ElectionData.new(options.voter_list, options.results)
election_data.create_csv
